extern void win32_dialog_set_text(HWND diag,int id,char *value);
extern void win32_dialog_get_text(HWND diag,int id,char *value,int value_len);
extern void win32_dialog_set_int(HWND diag,int id,int value);
extern int win32_dialog_get_int(HWND diag,int id);
extern void win32_dialog_set_float(HWND diag,int id,float value);
extern float win32_dialog_get_float(HWND diag,int id);
extern void win32_dialog_combo_add(HWND diag,int id,char *str);
extern void win32_dialog_combo_set_value(HWND diag,int id,int value);
extern int win32_dialog_combo_get_value(HWND diag,int id);
extern void win32_dialog_list_add(HWND diag,int id,char *str);
extern void win32_dialog_list_set_value(HWND diag,int id,int value);
extern int win32_dialog_list_get_value(HWND diag,int id);
extern void win32_dialog_enable(HWND diag,int id,bool enable);
extern void win32_dialog_set_focus(HWND diag,int id);
extern int win32_dialog_select_all(HWND diag,int id);
