#define IDC_STATIC							-1

// menus

#define IDR_MAIN_MENU						10
#define IDR_ACCELERATOR						11

#define ID_FILE_NEW							100
#define ID_FILE_OPEN						101
#define ID_FILE_CLOSE						102
#define ID_FILE_SAVE						103
#define ID_FILE_PREFERENCE					104
#define ID_FILE_EXIT						105

#define ID_EDIT_UNDO						200
#define ID_EDIT_SELECT_MORE					201

#define ID_MODEL_PREPARE_MODEL				300
#define ID_MODEL_CALC_BOXES					301
#define ID_MODEL_CALC_NORMAL				302
#define ID_MODEL_SCALE						303
#define ID_MODEL_FLIP_X						304
#define ID_MODEL_FLIP_Y						305
#define ID_MODEL_FLIP_Z						306
#define ID_MODEL_SWAP_XZ					307
#define ID_MODEL_SWAP_YZ					308
#define ID_MODEL_CENTER_XZ					309
#define ID_MODEL_FLOOR_Y					310
#define ID_MODEL_ADD_HIT_BOX				311

#define ID_VIEW_FRONT						400
#define ID_VIEW_LEFT						401
#define ID_VIEW_RIGHT						402
#define ID_VIEW_BACK						403
#define ID_VIEW_TOP							404
#define ID_VIEW_BOTTOM						405

#define ID_MESH_ADD							500	
#define ID_MESH_DUPLICATE					501
#define ID_MESH_IMPORT_OBJ					502
#define ID_MESH_REPLACE_OBJ					503
#define ID_MESH_ADD_MESH					504
#define ID_MESH_SCALE						505
#define ID_MESH_FLIP_X						506
#define ID_MESH_FLIP_Y						507
#define ID_MESH_FLIP_Z						508
#define ID_MESH_FLIP_U						509
#define ID_MESH_FLIP_V						510
#define ID_MESH_SWAP_XZ						511
#define ID_MESH_SWAP_YZ						512
#define ID_MESH_CENTER_XZ					513
#define ID_MESH_FLOOR_Y						514
#define ID_MESH_TESSELLATE					515

#define ID_VERTEX_SELECT_ALL				600
#define ID_VERTEX_SELECT_NOT_ATTACHED		601
#define ID_VERTEX_INVERT_NORMAL				602
#define ID_VERTEX_SET_NORMAL				603
#define ID_VERTEX_SET_NORMAL_OUT			604
#define ID_VERTEX_SET_NORMAL_IN				605
#define ID_VERTEX_CLEAR_BONE				606
#define ID_VERTEX_AUTO_SET_BONE				607
#define ID_VERTEX_HIDE_SELECTED				608
#define ID_VERTEX_HIDE_NON_SELECTED			609
#define ID_VERTEX_SHOW_ALL					610
#define ID_VERTEX_COLLAPSE					611
#define ID_VERTEX_DELETE					612
#define ID_VERTEX_DELETE_POLYGON			613
#define ID_VERTEX_MAKE_QUAD					614
#define ID_VERTEX_TESSELLATE_POLYGON		615

#define ID_BONE_ADD							700
#define ID_BONE_SET							701
#define ID_BONE_GOTO_PARENT					702

#define ID_POSE_NEW							800
#define ID_POSE_DUPLICATE					801
#define ID_POSE_CLEAR						802

#define ID_ANIMATION_NEW					900
#define ID_ANIMATION_DUPLICATE				901
#define ID_ANIMATION_SCALE_TIME				902
#define ID_ANIMATION_PLAY					903
#define ID_ANIMATION_PLAY_BLENDED			904

// dialogs

#define IDD_FILE_OPEN						1000
#define IDC_FILE_OPEN_TREE					1001

#define IDD_FILE_NEW						1010
#define IDC_FILE_NEW_NAME					1011
#define ID_FILE_NEW_NEW						1012

#define IDD_OBJ_IMPORT						1100
#define ID_OBJ_IMPORT_OK					1101
#define ID_OBJ_IMPORT_CANCEL				1102
#define IDC_OBJ_IMPORT_TYPE					1103
#define IDC_OBJ_IMPORT_AXIS					1104
#define IDC_OBJ_IMPORT_UNITS				1105

#define IDD_IMPORT_FINISH					1200
#define IDC_IMPORT_FINISH_HEIGHT			1201
#define ID_IMPORT_FINISH_OK					1202

#define IDD_PICK_SCALE						1300
#define IDC_PICK_SCALE_TYPE					1301
#define IDC_PICK_SCALE_X					1302
#define IDC_PICK_SCALE_Y					1303
#define IDC_PICK_SCALE_Z					1304
#define ID_PICK_SCALE_CANCEL				1305
#define ID_PICK_SCALE_OK					1306

#define IDD_SET_VERTEX_BONE					1400
#define IDC_SET_VERTEX_BONE_MAJOR_BONE		1401
#define IDC_SET_VERTEX_BONE_MINOR_BONE		1402
#define IDC_SET_VERTEX_BONE_FACTOR			1403
#define ID_SET_VERTEX_BONE_CANCEL			1404
#define ID_SET_VERTEX_BONE_OK				1405

#define IDD_SET_NORMAL						1500
#define IDC_SET_NORMAL_X					1501
#define IDC_SET_NORMAL_Y					1502
#define IDC_SET_NORMAL_Z					1503
#define ID_SET_NORMAL_CANCEL				1504
#define ID_SET_NORMAL_OK					1505

#define IDD_BLEND_ANIMATION					1600
#define IDC_BLEND_ANIMATION_1				1601
#define IDC_BLEND_ANIMATION_2				1602
#define IDC_BLEND_ANIMATION_3				1603
#define IDC_BLEND_ANIMATION_4				1604
#define ID_BLEND_ANIMATION_CANCEL			1605
#define ID_BLEND_ANIMATION_OK				1606

#define IDD_SCALE_ANIMATION					1701
#define IDC_SCALE_ANIMTION_TIME				1702
#define ID_SCALE_ANIMATION_CANCEL			1703
#define ID_SCALE_ANIMATION_OK				1704

#define IDD_PROPERTY_LIST					5000
#define IDC_PROPERTY_LIST_LIST				5001
#define ID_PROPERTY_LIST_NONE				5002
#define ID_PROPERTY_LIST_OK					5003

#define IDD_PROPERTY_STRING					5010
#define IDC_PROPERTY_STRING_STRING			5011
#define ID_PROPERTY_STRING_OK				5012

#define IDD_PROPERTY_CHORD					5020
#define IDC_PROPERTY_CHORD_X				5021
#define IDC_PROPERTY_CHORD_Y				5022
#define IDC_PROPERTY_CHORD_Z				5023
#define ID_PROPERTY_CHORD_OK				5024

