#define IDC_STATIC							-1

// menus

#define IDR_MAIN_MENU						10
#define IDR_ACCELERATOR						11

#define ID_FILE_NEW							100
#define ID_FILE_OPEN						101
#define ID_FILE_CLOSE						102
#define ID_FILE_SAVE						103
#define ID_FILE_PREFERENCE					104
#define ID_FILE_EXIT						105

#define ID_FILE_UNDO						200
#define ID_FILE_DELETE						201
#define ID_FILE_DUPLICATE					202
#define ID_EDIT_SELECT_MORE					203

#define ID_VIEW_FRONT						300
#define ID_VIEW_LEFT						301
#define ID_VIEW_RIGHT						302
#define ID_VIEW_BACK						303
#define ID_VIEW_TOP							304
#define ID_VIEW_BOTTOM						305
#define ID_VIEW_PERSPECTIVE					306
#define ID_VIEW_ORTHO						307
#define ID_VIEW_NORMAL_LAYER				308
#define ID_VIEW_LIGHT_MAP_LAYER				309
#define ID_VIEW_GOTO_SELECTION				310
#define ID_VIEW_GOTO_MAP_CENTER				311
#define ID_VIEW_CLIPPING					312
#define ID_VIEW_LIQUIDS						313
#define ID_VIEW_SPOT_SCENERY				314
#define ID_VIEW_LIGHT_SOUND_PARTICLE		315
#define ID_VIEW_NODES						316
#define ID_VIEW_SPLIT_HORIZONTAL			317
#define ID_VIEW_SPLIT_VERTICAL				318
#define ID_VIEW_REMOVE_PANEL				319

#define ID_MAP_CINEMA						400
#define ID_MAP_GROUP						401
#define ID_MAP_MOVEMENT						402
#define ID_MAP_RAISE_Y						403
#define ID_MAP_LOWER_Y						404
#define ID_MAP_CENTER						405
#define ID_MAP_RESET_UV						406
#define ID_MAP_RECALC_NORMAL				408
#define ID_MAP_CLEAR_LIGHT_MAP				409
#define ID_MAP_BUILD_LIGHT_MAP				410
#define ID_MAP_BUILD_LIQUID_REFLECTION_MAP	411
#define ID_MAP_RUN							412

#define ID_MESH_COMBINE						500
#define ID_MESH_SPLIT						501
#define ID_MESH_TESSELATE					502
#define ID_MESH_RESIZE						503
#define ID_MESH_REPOSITION					504
#define ID_MESH_RESIZE_TEXTURE				505
#define ID_MESH_FLIP_X						506
#define ID_MESH_FLIP_Y						507
#define ID_MESH_FLIP_Z						508
#define ID_MESH_ROTATE_X					509
#define ID_MESH_ROTATE_Y					510
#define ID_MESH_ROTATE_Z					511
#define ID_MESH_FREE_ROTATE					512
#define ID_MESH_RAISE_Y						513
#define ID_MESH_LOWER_Y						514
#define ID_MESH_SELECT_ALL_POLYGONS			515
#define ID_MESH_SNAP_TO_GRID				516
#define ID_MESH_SNAP_TO_CLOSEST_VERTEX		517
#define ID_MESH_RESET_UV					518
#define ID_MESH_WHOLE_UV					519
#define ID_MESH_SINGLE_STAMP_UV				520
#define ID_MESH_RECALC_NORMAL				521
#define ID_MESH_INVERT_NORMAL				522
#define ID_MESH_SET_NORMAL_OUT				523
#define ID_MESH_SET_NORMAL_IN				524

#define ID_POLYGON_PUNCH_HOLE				600
#define ID_POLYGON_TESSELATE				601
#define ID_POLYGON_SNAP_TO_GRID				602
#define ID_POLYGON_ROTATE_UV				603
#define ID_POLYGON_FLIP_U					604
#define ID_POLYGON_FLIP_V					605
#define ID_POLYGON_RECALC_NORMAL			606
#define ID_POLYGON_INVERT_NORMAL			607
#define ID_POLYGON_RESET_UV					608
#define ID_POLYGON_WHILE_UV					609
#define ID_POLYGON_SINGLE_STAMP_UV			610

#define ID_VERTEX_SNAP_TO_GRID				700

// dialogs

#define IDD_FILE_OPEN						1000
#define IDC_FILE_OPEN_TREE					1001

#define IDD_FILE_NEW						1010
#define IDC_FILE_NEW_NAME					1011
#define ID_FILE_NEW_NEW						1012

#define IDD_OBJ_IMPORT						1100
#define ID_OBJ_IMPORT_OK					1101
#define ID_OBJ_IMPORT_CANCEL				1102
#define IDC_OBJ_IMPORT_TYPE					1103
#define IDC_OBJ_IMPORT_AXIS					1104
#define IDC_OBJ_IMPORT_UNITS				1105

#define IDD_HEIGHT_MAP_IMPORT				1300
#define IDC_HEIGHT_MAP_IMPORT_DIVISIONS		1301
#define IDC_HEIGHT_MAP_IMPORT_SIZE			1302
#define IDC_HEIGHT_MAP_IMPORT_HEIGHT		1303
#define ID_HEIGHT_MAP_IMPORT_CANCEL			1304
#define ID_HEIGHT_MAP_IMPORT_OK				1305

#define IDD_CREATE_GRID						1400
#define IDC_CREATE_GRID_X_DIVISIONS			1401
#define IDC_CREATE_GRID_Y_DIVISIONS			1402
#define IDC_CREATE_GRID_Z_DIVISIONS			1403
#define ID_CREATE_GRID_CANCEL				1404
#define ID_CREATE_GRID_OK					1405

#define IDD_RESIZE							1500
#define IDC_RESIZE_X						1501
#define IDC_RESIZE_Y						1502
#define IDC_RESIZE_Z						1503
#define ID_RESIZE_CANCEL					1504
#define ID_RESIZE_OK						1505

#define IDD_FREE_ROTATE						1600
#define IDC_FREE_ROTATE_X_ROT				1601
#define IDC_FREE_ROTATE_Y_ROT				1602
#define IDC_FREE_ROTATE_Z_ROT				1603
#define ID_FREE_ROTATE_CANCEL				1604
#define ID_FREE_ROTATE_OK					1605

#define IDD_REPOSITION						1700
#define IDC_REPOSITION_X_TOPLEFT			1701
#define IDC_REPOSITION_Y_TOPLEFT			1702
#define IDC_REPOSITION_Z_TOPLEFT			1703
#define IDC_REPOSITION_X_BOTTOMRIGHT		1704
#define IDC_REPOSITION_Y_BOTTOMRIGHT		1705
#define IDC_REPOSITION_Z_BOTTOMRIGHT		1706
#define ID_REPOSITION_CANCEL				1707
#define ID_REPOSITION_OK					1708

#define IDD_RESIZE_TEXTURE					1800
#define IDC_RESIZE_TEXTURE_U				1801
#define IDC_RESIZE_TEXTURE_V				1802
#define ID_RESIZE_TEXTURE_CANCEL			1803
#define ID_RESIZE_TEXTURE_OK				1804

#define IDD_PROPERTY_STRING					5010
#define IDC_PROPERTY_STRING_STRING			5011
#define ID_PROPERTY_STRING_OK				5012

#define IDD_PROPERTY_CHORD					5020
#define IDC_PROPERTY_CHORD_X				5021
#define IDC_PROPERTY_CHORD_Y				5022
#define IDC_PROPERTY_CHORD_Z				5023
#define ID_PROPERTY_CHORD_OK				5024

