#define IDC_STATIC							-1

// dialogs

#define IDD_FILE_OPEN						1000
#define IDC_FILE_OPEN_TREE					1001

#define IDD_PROPERTY_STRING					5010
#define IDC_PROPERTY_STRING_STRING			5011
#define ID_PROPERTY_STRING_OK				5012

#define IDD_PROPERTY_CHORD					5020
#define IDC_PROPERTY_CHORD_X				5021
#define IDC_PROPERTY_CHORD_Y				5022
#define IDC_PROPERTY_CHORD_Z				5023
#define ID_PROPERTY_CHORD_OK				5024

